CREATE TABLE Aimers(Id int , FN VARCHAR(255) ,LN Varchar (255), CITY VARCHAR(255) , STATE VARCHAR(255) , PERCENTAGE INT ) ;

SELECT * FROM Aimers ;

ALTER TABLE Aimers DROP COLUMN  NAME ;

DROP TABLE Aimers;

INSERT INTO Aimers VALUES (1 ,'ROHIT' , 'SHARMA' , 'NAGPUR' , 'MAHARASHTRA' , 95) ;
INSERT INTO Aimers VALUES (2 ,'HARDIK' , 'PANDYA' , 'AHMDABAD' , 'GUJRAT' , 89) ;
INSERT INTO Aimers VALUES (3 ,'RISHABH' , 'PANT' , 'MUMBAI' , 'MAHARASHTRA' , 75) ;
INSERT INTO Aimers VALUES (4 ,'RAHUL' , 'DRAVID' , 'AKOLA' , 'MAHARASHTRA' , 95) ;
INSERT INTO Aimers VALUES (5 ,'KRUNAL' , 'PANDYA' , 'AHMDABAD' , 'GUJRAT' , 56) ;
INSERT INTO Aimers VALUES (6 ,'ARSHDEEP' , 'SINGH' , 'CHANDIGADH' , 'PUNJAB' , 97) ;
INSERT INTO Aimers VALUES (7 ,'VIRAT' , 'KOHLI' , 'NEW DELHI' , 'NEW DELHI' , 67) ;
INSERT INTO Aimers VALUES (8 ,'SURYKUMAR' , 'YADAV' , 'MUMBAI' , 'MAHARASHTRA' , 85) ;
INSERT INTO Aimers VALUES (9 ,'YUVRAJ' , 'SINGH' , 'CHANDHIGADH' , 'PUNJAB' , 45) ;
INSERT INTO Aimers VALUES (10 ,'IRFAN' , 'PATHAN' , 'AHMADNAGAR' , 'MAHARASHTRA' , 95) ;
INSERT INTO Aimers VALUES (11 ,'MS' , 'DHONI' , 'RANCHI' , 'KERAL' , 75) ;  

SELECT * FROM Aimers ;

SELECT CITY , STATE FROM AIMERS ;

SELECT DISTINCT STATE FROM AIMERS ; 

SELECT DISTINCT CITY FROM AIMERS ; 

SELECT COUNT (DISTINCT CITY ) FROM AIMERS ; 

SELECT * FROM AIMERS WHERE ROWNUM <=3 ; 


SELECT * FROM AIMERS WHERE ROWNUM <=9 ;

SELECT * FROM AIMERS FETCH FIRST 3 ROWS ONLY ;

SELECT COUNT (FN) FROM AIMERS ; 

SELECT COUNT (STATE) FROM AIMERS ; 

SELECT CITY FROM AIMERS ;

SELECT MIN (PERCENTAGE) FROM AIMERS ;

SELECT * FROM AIMERS ;

SELECT MAX (PERCENTAGE) FROM AIMERS ; 

SELECT SUM (PERCENTAGE) FROM AIMERS ;

SELECT AVG(PERCENTAGE) FROM AIMERS ;

SELECT * FROM AIMERS WHERE PERCENTAGE > 50 ;

SELECT * FROM AIMERS ORDER BY CITY ;

SELECT * FROM AIMERS ORDER BY FN ASC ;

SELECT * FROM AIMERS ORDER BY CITY DESC ; 

SELECT * FROM AIMERS ORDER BY LN DESC ; 

SELECT * FROM AIMERS ORDER BY PERCENTAGE ; 

SELECT * FROM AIMERS ORDER BY PERCENTAGE DESC ; 

SELECT * FROM AIMERS WHERE CITY = 'MUMBAI' ;

SELECT * FROM AIMERS WHERE FN='VIRAT'  ;

SELECT * FROM AIMERS WHERE PERCENTAGE > 50 ;

SELECT * FROM AIMERS WHERE LN='PANDYA' ;

SELECT * FROM AIMERS ;

SELECT * FROM AIMERS WHERE FN='HARDIK' OR LN='PANDYA' ;

SELECT * FROM AIMERS WHERE FN='HARDIK' AND LN='PANDYA' ;

SELECT * FROM AIMERS WHERE CITY LIKE 'A%' ; 

SELECT * FROM AIMERS WHERE CITY LIKE '%A' ; 

SELECT * FROM AIMERS ; 

SELECT * FROM AIMERS WHERE FN NOT LIKE  'A%' ;

SELECT * FROM AIMERS WHERE FN LIKE '%A%' ;

SELECT * FROM AIMERS WHERE FN LIKE'V%T' ;

SELECT * FROM AIMERS WHERE LN LIKE 'P%A' ;

SELECT * FROM AIMERS WHERE FN LIKE '%R' ;

SELECT * FROM AIMERS WHERE FN LIKE '%[RAT]' ;

SELECT * FROM AIMERS WHERE FN LIKE '_IRAT' ;

SELECT * FROM AIMERS WHERE FN LIKE 'H____K' ;

SELECT * FROM AIMERS ;

SELECT * FROM AIMERS WHERE FN LIKE 'H____K' OR LN LIKE 'P____A' ;

SELECT * FROM AIMERS WHERE FN IN ('HARDIK' , 'KRUNAL' , 'MS') ;

SELECT * FROM AIMERS WHERE LN NOT IN ('PANDYA' , 'DHONI' ) ; 

SELECT * FROM AIMERS WHERE ID BETWEEN 1 AND 5 ; 

INSERT INTO AIMERS VALUES ( 12,'HARBHAJAN','SINGH', 'CHANDIGADH','PUNJAB',79);

UPDATE  AIMERS  SET PERCENTAGE=90 WHERE CITY='AKOLA' ;

SELECT*FROM AIMERS ; 

UPDATE AIMERS SET FN='SHIKHAR' , LN='DHAWAN' WHERE PERCENTAGE=95 ;

UPDATE AIMERS SET FN='ROHIT' , LN='SHARMA' WHERE CITY='NAGPUR' ;

ALTER TABLE AIMERS ADD CATEGORY VARCHAR(255) ;

UPDATE AIMERS SET CATEGORY='PASS' WHERE PERCENTAGE > 60 ; 

UPDATE AIMERS SET CATEGORY='FAIL' WHERE PERCENTAGE < 60 ;

UPDATE AIMERS SET CATEGORY= 'FAIL' WHERE PERCENTAGE > 70 ;

SELECT * FROM AIMERS;

DELETE FROM AIMERS WHERE CATEGORY = 'FAIL' ;

SELECT * INTO CRICKS FROM AIMERS  ;

SELECT PERCENTAGE AS CRITERIA FROM AIMERS ;

SELECT LN FROM AIMERS UNION SELECT LN FROM ROCKSTAR ;

SELECT FN FROM AIMERS UNION SELECT FN FROM ROCKSTAR ;

SELECT FN FROM AIMERS UNION ALL SELECT FN FROM ROCKSTAR ;

TRUNCATE TABLE AIMERS ;

SELECT * FROM AIMERS ;

DROP TABLE AIMERS ;